#
#
# Looking for server-side hacks?
# Introducing CombatUtils!
#
# Plugin Author: ImproperIssues
# Idea Credits: ImproperIssues, obvWolf
#
#
config:
  plugin:
    prefix: "§7[§4CombatUtils§7]"
    custom-command-prefix-character: '>'
  gameplay:
    explosion-block-damage: true
    explosion-fire: true




