name: CombatUtils
version: '${version}'
main: me.improper.combatutils.CombatUtils
api-version: 1.17
authors: [ ImproperIssues ]
description: Adds "utils" for pvp combat.
website: https://github.com/ItziSpyder
permissions:
  combatutils.modules:
    description: Access to all combat util modules.
    default: op
commands:
  "#toggle":
    description: Toggle modules for CombatUtils
    usage: /toggle <module> [<on>|<off>]
    permission: combatutils.modules